void draw_screen(void);
void draw_heavy_page();
void draw_fast_page();
void draw_diary_page();
void draw_laundry_menu();
void build_buttons();
void mxt_handler(struct mxt_device *device, struct botao *botoes, uint Nbotoes);
uint32_t convert_axis_system_y(uint32_t touch_x);
uint32_t convert_axis_system_x(uint32_t touch_y);
static void mxt_init(struct mxt_device *device);
static void configure_lcd(void);
int processa_touch(struct botao *b, struct botao *rtn, uint N ,uint x, uint y );
void lock_callback(void);
void unlock_callback(void);
void slice_left_callback(void);
void slice_right_callback(void);
void lavagem_callback(void);
void play_pause_callback(void);
void home_callback(void);
void build_laundry_types();
void RTC_Handler(void);
void RTC_init();
void print_time(void);
void font_draw_text(tFont *font, const char *text, int x, int y, int spacing);
void draw_done_laundry();
void draw_working(int time_left);